# The latest versions are available at https://quiltmc.org/en/usage/latest-versions
[versions]
minecraft = "1.20.1"
quilt_mappings = "1.20.1+build.23"

quilt_loom = "1.6.8"
quilt_loader = "0.26.0"
shadow = "8.1.7"

quilted_fabric_api = "7.5.0+0.91.0-1.20.1"
mod_menu = "7.2.2"
quilt_parsers_json = "0.3.0"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt_mappings" }
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }

quilted_fabric_api = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api", version.ref = "quilted_fabric_api" }
mod_menu = { module = "com.terraformersmc:modmenu", version.ref = "mod_menu" }
quilt_parsers_json = { module = "org.quiltmc.parsers:json", version.ref = "quilt_parsers_json" }

[plugins]
quilt_loom = { id = "org.quiltmc.loom", version.ref = "quilt_loom" }
shadow = { id = "io.github.goooler.shadow", version.ref = "shadow" }
