name: Build Mod
on: push

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Eclipse Temurin 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Build with Gradle
      run: gradle build
    - name: Detonate JARs
      run: python ./ci/hissboom.py "./build/libs/*.jar"
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Build Artifacts
        path: build/libs
