name: Build Mod
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Eclipse Temurin 16
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '16'
    - name: Build with Gradle
      run: gradle build
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: build/libs
